server:
  port: 8080
spring:
  application:
    name: timtro

  datasource:
    url: jdbc:mysql://localhost:3306/tim_tro
    username: root
    password: 21112004
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update